spring:
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: ru.denis.atm.kafkaevents
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
server:
  port: 8081